name: Build and Deploy Docs

on:
  push:
    branches:
      - main  
      - docs

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'sphinx>=7.1.0' sphinx-rtd-theme myst-parser docutils sphinx-autodoc-typehints
          pip freeze  # Debug: show all installed packages
          
      - name: Build docs
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd docs
          make clean
          # Generate API documentation
          sphinx-apidoc -f -o source ../library_analyzer/
          make html
          # Debug: show the contents of the build directory
          ls -R build/html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html 