name: Build and Deploy Docs

on:
  push:
    branches:
      - main  
      - docs

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: transposon_silencing
          environment-file: env.yml
          auto-activate-base: false

      - name: Build docs
        shell: bash -l {0}
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          conda activate transposon_silencing
          # Debug: Print current directory and its contents
          pwd
          ls -la
          # Debug: Print Python path and try to import the package
          python -c "import sys; print('Python path:', sys.path); import library_analyzer; print('Package location:', library_analyzer.__file__)"
          cd docs
          make clean
          # Generate API documentation
          sphinx-apidoc -f -o source ../library_analyzer/
          make html SPHINXOPTS="-vvv"  # More verbose output for debugging
          # Debug: show the contents of the build directory
          ls -R build/html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html 